default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: todo_list_management_development

test:
  <<: *default
  database: todo_list_management_test

production:
  <<: *default
  database: todo_list_management_production
  username: $USER
  password: <%= ENV['TODO_LIST_MANAGEMENT_DATABASE_PASSWORD'] %>
